---
apiVersion: v1
kind: ConfigMap
metadata:
  name: phpipam-config
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  labels:
    app: phpipam
    service: phpipam
    component: phpipam
    id: phpipam-config
data:
  TZ: America/New_York
  IPAM_TRUST_X_FORWARDED: "true"
  SCAN_INTERVAL: 10m