---
apiVersion: v1
kind: Secret
metadata:
  name: phpipam-db-info
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  labels:
    app: phpipam
    service: phpipam-mariadb
    component: phpipam-mariadb
    id: phpipam-mariadb
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: s3cur3p4ssw0rd
  MYSQL_DATABASE: phpipam
  MYSQL_USER: phpipam
  MYSQL_PASSWORD: s3cur3p4ssw0rd

  IPAM_DATABASE_HOST: phpipam-mariadb
  IPAM_DATABASE_NAME: phpipam
  IPAM_DATABASE_USER: phpipam
  IPAM_DATABASE_PASS: s3cur3p4ssw0rd
