apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: phpipam

resources:
  - 00-namespace.yml
  - 01-pvc-db.yml
  - 02-configmap-ca-certs.yml
  - 02-configmap-env.yml
  - 02-secret-db.yml
  - 03-statefulset-mariadb.yml
  - 04-service-mariadb.yml
  - 05-deployment-web.yml
  - 05-deployment-cron.yml
  - 10-service-web.yml
  - 12-ingress.yml
  - 15-networkpolicies.yml
